version: "3.9"
   
services:
  db:
    image: postgres
    ports: 
      - "5432:5432"
    command: postgres -c listen_addresses='*'
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root

  web: &web
    build: .
    command: >
      sh -c "python NewsProject/manage.py makemigrations && 
      python NewsProject/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=db
    depends_on:
      - db
      - rabbitmq
      - celery_worker
  
  # rabbitmq:
  #   image: rabbitmq:3-management-alpine
  
  # Enable network for rabbitmq chart UI
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 15672:15672

  celery_worker:
    <<: *web
    command: >
      sh -c "cd NewsProject && 
      celery -A NewsProject worker --loglevel=info"
    ports: []
    depends_on:
      - rabbitmq
      - db
  
  # celery_beat:
  #   <<: *web
  #   command: >
  #     sh -c "cd NewsProject && 
  #     celery -A NewsProject beat --loglevel=info"
  #   ports: []
  #   depends_on:
  #     - rabbitmq
  #     - db
      
volumes: 
  db:
