# Generated by Django 3.2.6 on 2021-08-08 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NewsApi', '0005_auto_20210808_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='symbol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='NewsApi.symbol'),
        ),
    ]
