# Generated by Django 3.2.6 on 2021-08-10 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NewsApi', '0006_article_symbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='symbol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='NewsApi.symbol'),
        ),
    ]
