# Generated by Django 3.2.6 on 2021-08-12 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsApi', '0007_alter_article_symbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='symbol',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
